### ISSUE TITLE
Link to weights not working

### ISSUE THREAD

**Issue by ieee8023** [pirocv/xray_age#1]
Hello, I get the message "This shared file or folder link has been removed or is unavailable to you" when I try to access the link to the weights. Can you share them again?

Also, what is the license for the code and weights?

**Comment by pirocv** [comment]
Hello @ieee8023,

I am sorry for my late reply.
I have updated the download link and added the license file (Apache 2.0).

Thank you

**Comment by ieee8023** [comment]
Thanks, after I posted this I found the weights committed in the repo. 

Do you want to add a link to say that this model is available in TorchXRayVision? https://github.com/mlmed/torchxrayvision

**Comment by pirocv** [comment]
Hi,
That's a good idea. I will.
And thank you for citing my paper in the `riken.AgeModel` documentation!
